# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/structify',
                'doc_host': 'https://gautam-e.github.io',
                'git_url': 'https://github.com/gautam-e/structify',
                'lib_path': 'structify'},
  'syms': {'structify.core': {'structify.core.structured_output': ('core.html#structured_output', 'structify/core.py')}}}
