"""API to get structured output from a string using different LLM providers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['structured_output']

# %% ../nbs/00_core.ipynb 3
import os
from litellm import completion
from pydantic import BaseModel

# %% ../nbs/00_core.ipynb 4
def structured_output(model:str, # Model name, see examples here or LiteLLM docs for complete list
                      system_prompt:str, # Instructions for LLM to process the input string
                      user_prompt:str, # Input string that will be processed
                      response_format:BaseModel # User-defined Pydantic model to define output 
                     ) -> BaseModel :
    response = completion(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": user_prompt
            }
        ],
        response_format=response_format
    )
    return response_format.model_validate_json(response.choices[0].message.content)
